theme: null
permalink: pretty
slugify:
  mode: "latin"
  cased: false # <--- This forces all generated slugs to lowercase
exclude:
  - archived
collections:
  riffs:
    output: true
plugins:
  - jekyll-paginate-v2

pagination:
  enabled: true
  collection: 'riffs'     # Points directly to your _riffs collection
  per_page: 10            # Number of riffs per page
  permalink: '/riffs/page/:num/'  # Output path structure
  sort_field: 'date'
  sort_reverse: true      # Newest first